[[constraint]]
  name = "github.com/elastic/beats"
  version = "=6.6.0"

[[constraint]]
  name = "gopkg.in/bsm/sarama-cluster.v2"
  version = "2.1.15"

[[constraint]]
  name = "github.com/magefile/mage"
  version = "1.4.0"
